start transaction;
use library;
insert into `library`.`users` values(1, "johnsnow@gmail.com", "0960969090", "John", "Snow", "password1D", "USER");
insert into `library`.`users` values(2, "admin@gmail.com", "0961234567", "Василь", "Пупкін", "Admin1234", "ADMIN");
insert into `library`.`users` values(3, "kornik@gmail.com", "0909876543", "Михаил", "Корников", "qwerty123QWERTY", "ADMIN");
insert into `library`.`users` values(4, "stepanJ@imail.com", "0443243434", "Степан", "Портак", "12345678Qq", "USER");
insert into `library`.`users` values(5, "kenya@gmail.com", "0503323434", "Інокентій", "Пастернак", "Password1", "USER");
insert into `library`.`users` values(6, "gregor@gmail.com", "0930302099", "Грегорій", "Лінус", "Gsdikj213", "USER");
commit;

start transaction;
use library;
insert into `books` values(1, "Dune", "Fantasy-3-K");
insert into `books` values(2, "Data Science. Insider Information for Newbies", "IT-2-A");
insert into `books` values(3, "The witcher", "Fantasy-3-G");
insert into `books` values(4, "Blood elves", "Fantasy-3-G");
insert into `books` values(5, "Hour of Contempt", "Fantasy-3-G");
insert into `books` values(6, "Java. INDUSTRIAL PROGRAMMING", "IT-1-A");
insert into `books` values(7, "I am a robot", "Fantasy-2-I");
insert into `books` values(8, "Bicentennial man", "Fantasy-2-I");
insert into `books` values(9, "Stars like dust", "Fantasy-2-I");
insert into `books` values(10, "SQL - requests for mere mortals.", "IT-1-A");
insert into `books` values(11, "Java. Effective programming.", "IT-1-A");
insert into `books` values(12, "The Hitchhiker's Guide to the Galaxy", "Fantasy-3-B");
commit;
start transaction;
use library;
insert into `books_ua` values(1, "Дюна", "Fantasy-3-K");
insert into `books_ua` values(2, "Data Science. Инсайдерская информация для новичков", "IT-2-A");
insert into `books_ua` values(3, "Ведьмак", "Fantasy-3-G");
insert into `books_ua` values(4, "Кровь эльфов", "Fantasy-3-G");
insert into `books_ua` values(5, "Час Презрения", "Fantasy-3-G");
insert into `books_ua` values(6, "Java. ПРОМЫШЛЕННОЕ ПРОГРАММИРОВАНИЕ", "IT-1-A");
insert into `books_ua` values(7, "Я-робот", "Fantasy-2-I");
insert into `books_ua` values(8, "Двухсотлетний человек", "Fantasy-2-I");
insert into `books_ua` values(9, "Звезды как пыль", "Fantasy-2-I");
insert into `books_ua` values(10, "SQL - запросы для простых смертных.", "IT-1-A");
insert into `books_ua` values(11, "Java. Эффективное программирование.", "IT-1-A");
insert into `books_ua` values(12, "Автостопом по галактике", "Fantasy-3-B");
commit;

start transaction;
use library;
insert into `library`.`author` values(1, "Frank", "Gebert", NULL);
insert into `library`.`author` values(2, "Кетті", "Нілл", "О");
insert into `library`.`author` values(3, "Рейчел", "Шат",NULL);
insert into `library`.`author` values(4, " Анджей", "Сапковский", NULL);
insert into `library`.`author` values(5, "Николай", "Блинов", "Иванович");
insert into `library`.`author` values(6, "Валерий", "Романчик", "Станиславович");
insert into `library`.`author` values(7, "Айзек", "Азімов", NULL);
insert into `library`.`author` values(8, "Майкл", "Хернандес", "Дж.");
insert into `library`.`author` values(9, "Джон", "Вьескас", NULL);
insert into `library`.`author` values(10, "Джошуа", "Блох", NULL);
insert into `library`.`author` values(11, "Дуглас", "Адамс", NULL);
commit;
start transaction;
use library;
insert into `library`.`author_ua` values(1, "Френк", "Геберт", NULL);
insert into `library`.`author_ua` values(2, "Кетті", "Нілл", "О");
insert into `library`.`author_ua` values(3, "Рейчел", "Шат",NULL);
insert into `library`.`author_ua` values(4, " Анджей", "Сапковский", NULL);
insert into `library`.`author_ua` values(5, "Николай", "Блинов", "Иванович");
insert into `library`.`author_ua` values(6, "Валерий", "Романчик", "Станиславович");
insert into `library`.`author_ua` values(7, "Айзек", "Азімов", NULL);
insert into `library`.`author_ua` values(8, "Майкл", "Хернандес", "Дж.");
insert into `library`.`author_ua` values(9, "Джон", "Вьескас", NULL);
insert into `library`.`author_ua` values(10, "Джошуа", "Блох", NULL);
insert into `library`.`author_ua` values(11, "Дуглас", "Адамс", NULL);
commit;

start transaction;
use library;
insert into `library`.`authors2book` values(1, 1);
insert into `library`.`authors2book` values(2, 2);
insert into `library`.`authors2book` values(2, 3);
insert into `library`.`authors2book` values(3, 4);
insert into `library`.`authors2book` values(4, 4);
insert into `library`.`authors2book` values(5, 4);
insert into `library`.`authors2book` values(5, 5);
insert into `library`.`authors2book` values(6, 6);
insert into `library`.`authors2book` values(7, 7);
insert into `library`.`authors2book` values(8, 7);
insert into `library`.`authors2book` values(9, 7);
insert into `library`.`authors2book` values(10, 8);
insert into `library`.`authors2book` values(10, 9);
insert into `library`.`authors2book` values(11, 10);
insert into `library`.`authors2book` values(12, 11);
commit;

start transaction;
use library;
insert into `library`.`book_key_words` values(1, "fantasy");
insert into `library`.`book_key_words` values(2, "it");
insert into `library`.`book_key_words` values(3, "java");
insert into `library`.`book_key_words` values(4, "sql");
insert into `library`.`book_key_words` values(5, "data science");
commit;
start transaction;
use library;
insert into `library`.`book_key_words_ua` values(1, "fantasy");
insert into `library`.`book_key_words_ua` values(2, "it");
insert into `library`.`book_key_words_ua` values(3, "java");
insert into `library`.`book_key_words_ua` values(4, "sql");
insert into `library`.`book_key_words_ua` values(5, "data science");
commit;

start transaction;
use library;
insert into `library`.`keywords2book` values(1, 1);
insert into `library`.`keywords2book` values(2, 2);
insert into `library`.`keywords2book` values(2, 5);
insert into `library`.`keywords2book` values(3, 1);
insert into `library`.`keywords2book` values(4, 1);
insert into `library`.`keywords2book` values(5, 1);
insert into `library`.`keywords2book` values(6, 2);
insert into `library`.`keywords2book` values(6, 3);
insert into `library`.`keywords2book` values(7, 1);
insert into `library`.`keywords2book` values(8, 1);
insert into `library`.`keywords2book` values(9, 1);
insert into `library`.`keywords2book` values(10, 2);
insert into `library`.`keywords2book` values(10, 4);
insert into `library`.`keywords2book` values(11, 2);
insert into `library`.`keywords2book` values(11, 3);
insert into `library`.`keywords2book` values(12, 1);
commit;
start transaction;
use library;
insert into `library`.`taken_books` values(1, 2,3,'2018-12-01','2019-01-01');
insert into `library`.`taken_books` values(4, 2,6,'2018-12-08','2019-01-08');
insert into `library`.`taken_books` values(5, 3,10,'2018-12-11','2019-01-11');
commit;
start transaction;
use library;
insert into `library`.`book_request` values(6, 4);
insert into `library`.`book_request` values(4, 4);
commit;